server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/YOUR_DB
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD

  jpa:
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL
    password: YOUR_EMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  secret: YOUR_JWT_SECRET
  access-token-expiration: 600000
  refresh-token-expiration: 86400000
